# Generated by Django 4.1.13 on 2024-04-26 04:48

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import search.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patients",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("age", models.IntegerField()),
                ("sex", models.CharField(max_length=10)),
                ("adult_bmi", models.FloatField(blank=True, null=True)),
                ("child_weight", models.FloatField(blank=True, null=True)),
                ("child_height", models.FloatField(blank=True, null=True)),
                (
                    "respiratory_data",
                    djongo.models.fields.ArrayField(
                        blank=True,
                        model_container=search.models.RespiratoryData,
                        null=True,
                    ),
                ),
                ("average_cycle_duration", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "search_patients",
            },
        ),
        migrations.CreateModel(
            name="RespiratoryData",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("recording_index", models.CharField(max_length=3)),
                ("chest_location", models.CharField(max_length=2)),
                ("acquisition_model", models.CharField(max_length=2)),
                ("recording_equipment", models.CharField(max_length=20)),
                ("annotation_file", models.CharField(max_length=255)),
                ("respiratory_cycles", djongo.models.fields.JSONField()),
                ("sound_file_path", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis_name", models.CharField(max_length=100)),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="search.patients",
                    ),
                ),
            ],
            options={
                "db_table": "search_diagnosis",
            },
        ),
    ]
