# Generated by Django 4.1.13 on 2024-04-16 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="audio_files/")),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "search_audiofile",
            },
        ),
        migrations.CreateModel(
            name="Patients",
            fields=[
                ("patient", models.AutoField(primary_key=True, serialize=False)),
                ("age", models.IntegerField()),
                ("sex", models.CharField(max_length=10)),
                ("adult_bmi", models.FloatField(blank=True, null=True)),
                ("child_weight", models.FloatField(blank=True, null=True)),
                ("child_height", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "search_patients",
            },
        ),
        migrations.CreateModel(
            name="RespiratoryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recording_index", models.IntegerField()),
                ("chest_location", models.CharField(max_length=50)),
                ("acquisition_model", models.CharField(max_length=50)),
                ("recording_equipment", models.CharField(max_length=100)),
                ("annotation_file", models.CharField(max_length=255)),
                ("sound_file_path", models.CharField(max_length=255)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respiratory_data",
                        to="search.patients",
                    ),
                ),
            ],
            options={
                "db_table": "search_respiratory_data",
            },
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis_name", models.CharField(max_length=100)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="search.patients",
                    ),
                ),
            ],
            options={
                "db_table": "search_diagnosis",
            },
        ),
    ]
