# Generated by Django 5.0.4 on 2024-04-15 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recording_index", models.IntegerField()),
                ("chest_location", models.CharField(max_length=100)),
                ("acquisition_mode", models.CharField(max_length=100)),
                ("recording_equipment", models.CharField(max_length=100)),
                ("file_path", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_number", models.IntegerField(unique=True)),
                ("age", models.IntegerField()),
                ("sex", models.CharField(max_length=10)),
                ("bmi", models.FloatField(blank=True, null=True)),
                ("child_weight", models.FloatField(blank=True, null=True)),
                ("child_height", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("begin_cycle", models.FloatField()),
                ("end_cycle", models.FloatField()),
                ("crackles", models.BooleanField()),
                ("wheezes", models.BooleanField()),
                (
                    "audio_recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="search.audiorecording",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disease", models.CharField(max_length=100)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="search.patient"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="audiorecording",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="search.patient"
            ),
        ),
    ]
