# Generated by Django 5.0.4 on 2024-04-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_audiorecording_patient_annotation_diagnosis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofile",
            name="filename",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
